# https://github.com/tddschn/install-easygraph
# https://github.com/marketplace/actions/install-easygraph
name: 'Install EasyGraph'
description: 'Action that build and install python-easygraph from source (https://github.com/easy-graph/Easy-Graph)'
branding:
  icon: 'download-cloud'
  color: 'green'
inputs:
  cpp-binding-framework:  # id of input
    description: "The framework used to build easygraph's C++ binding"
    required: false
    default: "pybind11"
  # easygraph-checkout-path:
  #   default: "Easy-Graph"
  #   description: 'The path to checkout the Easy-Graph repository'
  #   required: false
  boost-version:
    default: "1.79.0"
    description: 'The version of boost to use'
    required: false

runs:
  using: "composite"
  steps:
    - name: Create a temporary dir for checking out
      id: tempdir
      run: |
        echo '::group::Creating temp dir'
        EG_TMP_DIR="$(mktemp --directory)"
        echo "EG_TMP_DIR: $EG_TMP_DIR"
        echo "::set-output name=tmp-dir::$EG_TMP_DIR"
        echo 'moving temp dir under workspace'
        mkdir -p -v "$GITHUB_WORKSPACE/tmp"
        mv -v "$EG_TMP_DIR" "$GITHUB_WORKSPACE/tmp"
        echo '::endgroup::'
      shell: bash
    - name: checkout Easy-Graph master branch
      if: inputs.cpp-binding-framework == 'boost-python'
      uses: actions/checkout@v3
      with:
        repository: easy-graph/Easy-Graph
        # path: ${{ inputs.easygraph-checkout-path }}
        # uses tmp-dir
        path: ${{ steps.tempdir.outputs.tmp-dir }}
        ref: 'master'

    - name: checkout Easy-Graph pybind11 branch
      if: inputs.cpp-binding-framework == 'pybind11'
      uses: actions/checkout@v3
      with:
        repository: easy-graph/Easy-Graph
        # path: ${{ inputs.easygraph-checkout-path }}
        path: ${{ steps.tempdir.outputs.tmp-dir }}
        ref: 'pybind11'
    # - run: |
    #     echo '::endgroup::'
    #   shell: bash

    - name: install easygraph common dependencies
      shell: bash
      run: |          
        echo '::group::Installing common dependencies'
        pip install pytest
        pip install Pillow
        pip install kiwisolver
        pip install gensim
        pip install lxml
        echo '::endgroup::'

    - name: build and install easygraph (pybind11)
      if: inputs.cpp-binding-framework == 'pybind11'
      shell: bash
      # working-directory: ${{ inputs.easygraph-checkout-path }}
      working-directory: '${{ steps.tempdir.outputs.tmp-dir }}'
      run: |          
        echo '::group::Building and installing easygraph (pybind11)'
        pip install pybind11
        python setup.py build_ext
        python setup.py install
        echo '::endgroup::'

    - name: build and install easygraph (boost-python)
      if: inputs.cpp-binding-framework == 'boost-python'
      shell: bash
      env:
        BOOST_VERSION: ${{ inputs.boost-version }}
      # working-directory: ${{ inputs.easygraph-checkout-path }}
      working-directory: '${{ steps.tempdir.outputs.tmp-dir }}'
      run: |          
        PYTHON_VERSION="$(python -V | cut -d' ' -f2 | cut -d'.' -f1-2)"
        PYTHON_VERSION_ABBR=${PYTHON_VERSION//./}
        BOOST_VERSION_ALIAS=boost_${BOOST_VERSION//./_}

        echo '::group::Versions info'
        echo "PYTHON_VERSION: ${PYTHON_VERSION}"
        echo "PYTHON_VERSION_ABBR: ${PYTHON_VERSION_ABBR}"
        echo "BOOST_VERSION: ${BOOST_VERSION}"
        echo "BOOST_VERSION_ALIAS: ${BOOST_VERSION_ALIAS}"
        echo '::endgroup::'

        echo '::group::Building and installing easygraph (boost-python)'

        sudo apt-get update
        sudo apt-get install gcc -y
        sudo apt-get install g++ -y
        wget https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/${BOOST_VERSION_ALIAS}.tar.gz
        tar -xf ${BOOST_VERSION_ALIAS}.tar.gz
        cd ${BOOST_VERSION_ALIAS}
        ./bootstrap.sh --with-python=python
        sudo ./b2 cxxflags="-fPIC" install --with-python
        
        sudo ln -s /usr/local/lib/libboost_python${PYTHON_VERSION_ABBR}.a /usr/local/lib/libboost_python.a

        cd -

        python setup.py build_ext -l boost_python -L "/usr/local/lib" -I "/usr/local/include"
        python setup.py install
        echo '::endgroup::'
    
    - name: Remove temp dir
      run: |
        echo '::group::Removing temp dir'
        rm -rfv '${{ steps.tempdir.outputs.tmp-dir }}'
        echo '::endgroup::'
      shell: bash
      

