name: Test the install-easygraph Action
on: 
  push:
  workflow_dispatch:
    # inputs:
    #   cpp-binding-framework: # id of input
    #     description: "The framework used to build easygraph's C++ binding"
    #     required: false
    #     default: "pybind11"
    #     type: choice
    #     options:
    #       - "pybind11"
    #       - "boost-python"
    #   easygraph-checkout-path:
    #     default: "Easy-Graph"
    #     description: 'The path to checkout the Easy-Graph repository'
    #     required: false
    #     type: string
jobs:
  test-install-easygraph:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        cpp-binding-framework: ["pybind11", "boost-python"]
    steps:
      # - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
      - name: 'Run install-easygraph - ${{ matrix.cpp-binding-framework }}'
        uses: tddschn/install-easygraph@master
        with:
          cpp-binding-framework: '${{ matrix.cpp-binding-framework }}'
  