name: Test the install-easygraph Action
on: 
  push:
  workflow_dispatch:
    # inputs:
    #   cpp-binding-framework: # id of input
    #     description: "The framework used to build easygraph's C++ binding"
    #     required: false
    #     default: "pybind11"
    #     type: choice
    #     options:
    #       - "pybind11"
    #       - "boost-python"
    #   easygraph-checkout-path:
    #     default: "Easy-Graph"
    #     description: 'The path to checkout the Easy-Graph repository'
    #     required: false
    #     type: string
jobs:
  pybind11:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '{{ matrix.python-version }}'
      - name: 'Test install-easygraph - pybind11'
        uses: tddschn/install-easygraph
        with:
          cpp-binding-framework: 'pybind11'
  
  boost-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        # boost-version: ["1.69.0", "1.70.0", "1.71.0", "1.72.0", "1.73.0", "1.74.0", "1.75.0", "1.76.0", "1.77.0", "1.78.0", "1.79.0"]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '{{ matrix.python-version }}'
      - name: 'Test install-easygraph - boost-python'
        uses: tddschn/install-easygraph
        with:
          cpp-binding-framework: 'boost-python'
          # boost-version: '{{ matrix.boost-version }}'