name: Test the install-easygraph Action
on: 
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
    # inputs:
    #   cpp-binding-framework: # id of input
    #     description: "The framework used to build easygraph's C++ binding"
    #     required: false
    #     default: "pybind11"
    #     type: choice
    #     options:
    #       - "pybind11"
    #       - "boost-python"
    #   easygraph-checkout-path:
    #     default: "Easy-Graph"
    #     description: 'The path to checkout the Easy-Graph repository'
    #     required: false
    #     type: string
jobs:
  test-install-easygraph:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        cpp-binding-framework: ["pybind11", "boost-python"]
    steps:
      # - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
      - name: 'Run install-easygraph - ${{ matrix.cpp-binding-framework }}'
        id: 'test'
        uses: tddschn/install-easygraph@master
        with:
          cpp-binding-framework: '${{ matrix.cpp-binding-framework }}'
      - name: Debug on failure
        if: ${{ failure() }}
        shell: bash
        working-directory: '${{ steps.test.outputs.eg-egg-dir-path }}'
        env: 
          SITE_PACKAGES_PATH: '${{ steps.test.outputs.site-packages-path }}'
          EG_EGG_DIR_PATH: '${{ steps.test.outputs.eg-egg-dir-path }}'
        run: |
          echo "SITE_PACKAGES_PATH: ${{ env.SITE_PACKAGES_PATH }}"
          echo "EG_EGG_DIR_PATH: ${{ env.EG_EGG_DIR_PATH }}"

          echo '::group::inside eg-egg-dir-path'
          pwd
          tree -L2
          echo '::endgroup::'
          
          echo '::group::inside site-packages-path'
          cd ..
          pwd
          ls -la
          echo '::endgroup::'
      - name: Setup tmate session
        if: "failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled"
        uses: mxschmitt/action-tmate@v3
        env: 
          SITE_PACKAGES_PATH: '${{ steps.test.outputs.site-packages-path }}'
          EG_EGG_DIR_PATH: '${{ steps.test.outputs.eg-egg-dir-path }}'
        with:
          limit-access-to-actor: true
          


  